(function(g){var window=this;'use strict';var G_l=function(G,B){if(!Number.isFinite(G))return String(G);G=String(G);var a=G.indexOf(".");a===-1&&(a=G.length);var V=G[0]==="-"?"-":"";V&&(G=G.substring(1));return V+(0,g.VfJ)("0",Math.max(0,B-a))+G},BN$=function(){return{Z:"svg",
N:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},D:[{Z:"path",N:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},az2=function(){return{Z:"svg",
N:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},D:[{Z:"path",N:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},xh$=function(G){typeof G==="number"?(this.date=VJ9(G,0,1),p5(this,1)):g.Ag(G)?(this.date=VJ9(G.getFullYear(),G.getMonth(),G.getDate()),p5(this,G.getDate())):(this.date=new Date(g.G$()),G=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),p5(this,G))},VJ9=function(G,B,a){B=new Date(G,B,a);
G>=0&&G<100&&B.setFullYear(B.getFullYear()-1900);return B},p5=function(G,B){G.getDate()!=B&&G.date.setUTCHours(G.date.getUTCHours()+(G.getDate()<B?1:-1))},Ux=function(G,B){g.uq.call(this,G,{Z:"div",
J:"ytp-reminder-menu",N:{role:"menu",tabindex:"-1"},D:[{Z:"div",J:"ytp-reminder-menu-contents",D:[{Z:"div",J:"ytp-reminder-menu-items"}]}]},100,!0);this.j=B;this.C=[];this.menuPopupRenderer=void 0;this.items=this.d1("ytp-reminder-menu-items");this.hide()},hU9=function(G){return(G.menuPopupRenderer&&G.menuPopupRenderer.items||[]).reduce(function(B,a){a&&a.menuServiceItemRenderer&&B.push(a.menuServiceItemRenderer);
return B},[])},Ox=function(G){g.T.call(this,{Z:"div",
D:[{Z:"button",bL:["ytp-offline-slate-button","ytp-button"],D:[{Z:"div",J:"ytp-offline-slate-button-icon",cS:"{{icon}}"},{Z:"div",J:"ytp-offline-slate-button-text",cS:"{{text}}"}]}]});this.T=G;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.X=void 0;this.G=this.j=null;(this.L=this.d1("ytp-offline-slate-button"))&&this.K(this.L,"click",this.W);this.hide()},Wcl=function(G,B,a){!G.toggleButtonRenderer&&B&&B.toggleButtonRenderer?G.toggleButtonRenderer=B.toggleButtonRenderer:
B&&B.toggleButtonRenderer||(G.toggleButtonRenderer=null);
!G.upcomingEventReminderButtonRenderer&&a&&g.u(a,eUf)?G.upcomingEventReminderButtonRenderer=g.u(a,eUf):a&&g.u(a,eUf)||(G.upcomingEventReminderButtonRenderer=null);Ex(G)},Ex=function(G){if(G.toggleButtonRenderer){var B=G.toggleButtonRenderer;
if(B.isToggled){var a=B.toggledText?g.tU(B.toggledText):"";G.update({text:a,icon:w2C(B.toggledIcon)})}else a=B.defaultText?g.tU(B.defaultText):"",G.update({text:a,icon:w2C(B.defaultIcon)});G.show()}else G.upcomingEventReminderButtonRenderer?(B=Kch(G))?(a=B.text?g.tU(B.text):"",G.update({text:a,icon:w2C(B.icon)}),G.show()):G.hide():G.hide()},k_J=function(G,B,a){G.G||(G.G=new g.MM(G.T.U().c9));
var V={context:g.l_(G.G.config_||g.Ki())};g.y0()&&(V.context.clientScreenNonce=g.y0());V.params=a;g.Gs(G.G,B,V,{timeout:5E3,onSuccess:function(){G.upcomingEventReminderButtonRenderer&&G.X&&(G.upcomingEventReminderButtonRenderer.currentState=G.X,G.X=void 0)},
onError:function(){lz$(G)},
onTimeout:function(){lz$(G)}})},lz$=function(G){G.toggleButtonRenderer?(G.toggleButtonRenderer.isToggled=!G.toggleButtonRenderer.isToggled,Ex(G)):G.upcomingEventReminderButtonRenderer&&(G.X=void 0,Ex(G))},w2C=function(G){if(!G)return null;
switch(G.iconType){case "NOTIFICATIONS":return BN$();case "NOTIFICATIONS_NONE":return az2();case "NOTIFICATIONS_ACTIVE":return g.jT();default:return null}},Kch=function(G){if(!G.upcomingEventReminderButtonRenderer)return null;
var B=G.X||G.upcomingEventReminderButtonRenderer.currentState;G=g.m(G.upcomingEventReminderButtonRenderer.states||[]);for(var a=G.next();!a.done;a=G.next())if((a=g.u(a.value,NN3))&&a.state===B&&a.button&&g.u(a.button,g.ZU))return g.u(a.button,g.ZU);return null},dhW=function(G){g.T.call(this,{Z:"div",
J:"ytp-offline-slate",D:[{Z:"div",J:"ytp-offline-slate-background"},{Z:"div",J:"ytp-offline-slate-bar",D:[{Z:"span",J:"ytp-offline-slate-icon",D:[{Z:"svg",N:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},D:[{Z:"path",N:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{Z:"circle",N:{cx:"12",cy:"12",r:"3"}}]}]},{Z:"span",J:"ytp-offline-slate-messages",D:[{Z:"div",J:"ytp-offline-slate-main-text",N:{"aria-label":"{{label}}"},cS:"{{mainText}}"},{Z:"div",J:"ytp-offline-slate-subtitle-text",cS:"{{subtitleText}}"}]},{Z:"span",J:"ytp-offline-slate-buttons"}]},{Z:"button",bL:["ytp-offline-slate-close-button","ytp-button"],D:[g.pr()]},{Z:"button",bL:["ytp-offline-slate-open-button","ytp-button"],D:[g.gI()]}]});var B=this;this.api=G;this.j=this.X=null;this.background=this.d1("ytp-offline-slate-background");
this.C=this.d1("ytp-offline-slate-bar");this.L=new g.J8(function(){g.hi(B.C,"ytp-offline-slate-bar-fade")},15E3);
this.W=!1;this.G=new g.J8(function(){g.hi(B.element,"ytp-offline-slate-collapsed")},15E3);
g.X(this,this.G);g.X(this,this.L);this.countdownTimer=new g.J8(this.PO,1E3,this);this.K(G,"presentingplayerstatechange",this.DP);this.K(G,"livestatedata",this.uL);this.K(this.d1("ytp-offline-slate-close-button"),"click",function(){g.hi(B.element,"ytp-offline-slate-collapsed")});
this.K(this.d1("ytp-offline-slate-open-button"),"click",function(){g.WC(B.element,"ytp-offline-slate-collapsed")});
this.hide();G=this.getVideoData();G.getPlayerResponse()&&(G=G.getPlayerResponse().playabilityStatus)&&this.uL(G);G=this.api.getPresentingPlayerType()===8&&!this.getVideoData().Wh;var a=this.api.getPresentingPlayerType()===8;g.Km(this.element,"ytp-offline-slate-premiere-trailer",G);g.Km(this.element,"ytp-offline-slate-hide-background",a)},Cch=function(G,B,a){if(B){var V=B.subtitleText!=null?g.tU(B.subtitleText):"";
a=a?a:B.mainText!=null?g.tU(B.mainText):"";var x,h,e,w;B=(w=(x=B.mainText)==null?void 0:(h=x.accessibility)==null?void 0:(e=h.accessibilityData)==null?void 0:e.label)!=null?w:a;G.update({mainText:a,subtitleText:V,label:B});g.Km(G.element,"ytp-offline-slate-single-text-line",!V);g.Km(G.C,"ytp-offline-slate-bar-hidden",!a&&!V)}},jm=function(G,B){var a=(0,g.yT)();
this.module="heartbeat";this.trigger=G;this.j=B;this.C=a},p2k=function(G){g.go.call(this,G);
var B=this;this.W=!1;this.V=0;this.B=!1;this.X=new g.J8(function(){zUh(B)},0);
this.j=this.heartbeatParams=null;this.G=!1;this.L=new g.Oz(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.zH=new g.MM(void 0);this.attestationResponse=Promise.resolve(void 0);this.Y=Promise.resolve(void 0);this.utcOffsetMinutes=-(new xh$).getTimezoneOffset();this.C=new g.Zh(this);g.X(this,this.X);g.X(this,this.C);tJ7(this);mh3(this);this.C.K(G,"heartbeatparams",this.T5);this.C.K(G,"presentingplayerstatechange",this.SU);this.C.K(G,"videoplayerreset",this.hm);this.C.K(G,g.hm("heartbeat"),
this.onCueRangeEnter);this.G&&this.j&&Iz$(this,void 0,this.j);var a=new g.V1(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),V=new g.V1(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});G.z1([a,V]);gHs(this)},gHs=function(G){var B=G.getVideoData();
!B.S("use_rta_for_player")&&B.dQ&&(B=B.botguardData)&&g.Zk(B,G.player.U())},Uhk=function(G){var B,a;
return g.v(function(V){if(V.j==1)return g.f(V,g.StX(),2);if(!V.X)return G.sequenceNumber>=3?V.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):V.return(void 0);B=G.getVideoData();a={};return V.return(g.D5B((a.cpn=B.clientPlaybackNonce,a.encryptedVideoId=B.videoId||"",a),1500))})},tJ7=function(G){var B=G.getVideoData();
if(B.dQ)if(B.S("use_rta_for_player"))G.attestationResponse=Uhk(G);else if(B=new g.Df9(B),g.vp.isInitialized()||G.sequenceNumber>=3){var a=Promise,V=a.resolve,x=null;if(B.videoData.N4){var h=g.SeH(B);if(h){x={};var e={};h=h.split("&");h=g.m(h);for(var w=h.next();!w.done;w=h.next())w=w.value.split("="),w.length===2&&(e[w[0]]=w[1]);e.r1a&&(x.webResponse=e.r1a);e.r1c&&(x.error=OXC[Number(e.r1c)]);x.challenge=B.videoData.N4}}G.attestationResponse=V.call(a,x||void 0)}},EHh=function(G){var B=G.getVideoData();
if(!g.gB(G.getVideoData())||B.zE)return!1;if(B.B){G=B.B.flavor==="playready"&&B.S("html5_innertube_heartbeats_for_playready");var a=B.B.flavor==="widevine"&&B.S("html5_innertube_heartbeats_for_widevine");B=g.$D(B.B)&&B.S("html5_innertube_heartbeats_for_fairplay");return!(G||a||B)}return!0},jCh=function(G){if(EHh(G))return!!G.heartbeatParams;
var B=G.getVideoData();return!g.gB(G.getVideoData())||B.d_||B.Km?!!B.heartbeatToken:!1},bJ=function(G,B){if(!G.X.isActive()&&G.W){var a=G.getVideoData();
if(jCh(G)||a.isLivePlayback){if(B===void 0)if(G.B)if(G.G)B=7500;else{var V;B=((V=G.heartbeatParams)==null?0:V.interval)?G.heartbeatParams.interval*1E3:G.getVideoData().qr||6E4}else B=1E3;G.X.start(B)}}},nHa=function(G,B,a){B.Nk&&(a=g.LJ(a,{internalipoverride:B.Nk}));
var V={cpn:B.clientPlaybackNonce};B.contextParams&&(V.context_params=B.contextParams);B.fh&&(V.kpt=B.fh);a=g.LJ(a,V);g.bm(a,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(x){if(!G.X.isActive()&&yf(G)){G.L.reset();G.sequenceNumber++;x=x.responseText;var h=bXs(x);if(h){G.player.pN("onHeartbeat",h);var e=h.status==="ok"?h.stop_heartbeat?2:0:h.status==="stop"?1:h.status==="live_stream_offline"?0:-1}else e=(e=x.match(yL8))?e[1]==="0"?0:1:-1;cL9(G,void 0,h,x,e)}},
onError:function(x){yf(G)&&cc(G,!0,"net-"+x.status)},
onTimeout:function(){yf(G)&&cc(G,!0,"timeout")},
withCredentials:!0})},zUh=function(G){var B,a;
g.v(function(V){B=G.player.U();a=G.getVideoData();if(!yf(G))return V.return();if(EHh(G))return fz2(G,B,a),V.kf(0);tJ7(G);return g.f(V,HXC(G,B,a),0)})},fz2=function(G,B,a){var V;
if((V=G.heartbeatParams)!=null&&V.url){var x=g.LJ(G.heartbeatParams.url,{request_id:g.$IX()});a.XJ&&(x=g.LJ(x,{vvt:a.XJ}),a.mdxEnvironment&&(x=g.LJ(x,{mdx_environment:a.mdxEnvironment})));g.Vm(B,a.oauthToken).then(function(h){h&&(x=g.LJ(x,{access_token:h}));nHa(G,a,x)})}},yf=function(G){var B=G.getVideoData();
return G.player.getPresentingPlayerType()===3||g.F(G.player.getPlayerStateObject(G.getPlayerType()),4)?!1:jCh(G)||B.isLivePlayback?!0:(n5(G),!1)},HXC=function(G,B,a){var V,x,h,e,w,K,l,k,N,d,C,z,p,O,b,c,H,R,q,A;
return g.v(function(J){if(J.j==1)return V="player/heartbeat",h={videoId:a.videoId,sequenceNumber:G.sequenceNumber,heartbeatServerData:(x=G.XJ)!=null?x:a.heartbeatServerData},G.Y=G.attestationResponse,a.dQ?g.f(J,G.Y,3):J.kf(2);J.j!=2&&(h.attestationResponse=J.X);e=g.hK(a);K=(w=e.client)!=null?w:{};K.utcOffsetMinutes=G.utcOffsetMinutes;h.context=e;h.cpn=a.clientPlaybackNonce;if(l=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)K.timeZone=l;k={heartbeatChecks:[]};
if(N=a.getPlayerResponse())a.heartbeatToken&&(h.heartbeatToken=a.heartbeatToken),(d=N.playabilityStatus)&&(C=d.liveStreamability)&&C.liveStreamabilityRenderer&&k.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");a.heartbeatToken&&k.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.jQ(B)&&(k.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),z=vH$(G),p={},z!==null&&(p.clientPlayerPositionUtcMillis=z),b=(O=G.player.Ch())==null?void 0:g.v$(O),H=((c=b)==null?void 0:c.freePreviewWatchedDuration)||
0,H>0&&(p.freePreviewWatchedDuration={seconds:""+H}),k.unpluggedParams=p);h.heartbeatRequestParams=k;a.isLivePlayback?(R=vH$(G),R!==null&&(h.playbackState||(h.playbackState={}),h.playbackState.playbackPosition={utcTimeMillis:R})):B.S("enable_heartbeat_vod_playback_position")&&(q=Dha(G),q!==null&&(h.playbackState||(h.playbackState={}),h.playbackState.playbackPosition={streamTimeMillis:q}));G.player.publish("heartbeatRequest",h);A={timeout:3E4,onSuccess:function(xB){if(!G.X.isActive()&&yf(G)){var Wz=
G.getVideoData(),GK=Wz.dQ&&G.Y==null,Q;Wz.dQ=!((Q=xB.heartbeatAttestationConfig)==null||!Q.requiresAttestation)||GK;GK=xB.playabilityStatus;Q=JSON.stringify(GK)||"{}";xB.authenticationMismatch&&G.player.FJ("authshear",{});var M=-1;var I=xB.playabilityStatus;I&&(G.player.pN("onHeartbeat",I),I.status==="OK"?M=xB.stopHeartbeat?2:0:I.status==="UNPLAYABLE"?M=1:I.status==="LIVE_STREAM_OFFLINE"&&(M=0));G.sequenceNumber&&M===-1||G.L.reset();G.sequenceNumber++;xB.heartbeatServerData&&(G.XJ=xB.heartbeatServerData);
Wz.pm=xB;(I=xB.playerCueRangeSet)&&g.il(Wz,I);xB.playerCueRanges&&xB.playerCueRanges.length>0&&(Wz.cueRanges=xB.playerCueRanges);var L,ux;((L=xB.progressBarConfig)==null?0:L.progressBarStartPosition)&&((ux=xB.progressBarConfig)==null?0:ux.progressBarEndPosition)&&(Wz.progressBarStartPosition=xB.progressBarConfig.progressBarStartPosition,Wz.progressBarEndPosition=xB.progressBarConfig.progressBarEndPosition);Wz.compositeLiveIngestionOffsetToken=xB.compositeLiveIngestionOffsetToken;xB.compositeLiveStatusToken!==
Wz.compositeLiveStatusToken&&(Wz.compositeLiveStatusToken=xB.compositeLiveStatusToken);Wz.publish("dataupdated");cL9(G,xB,GK,Q,M)}},
onError:function(xB){yf(G)&&cc(G,!0,"net-"+xB.status)},
onTimeout:function(){yf(G)&&cc(G,!0,"timeout")}};
g.Vm(B,g.uv(a)).then(function(xB){xB&&(A.L4="Bearer "+xB);g.Gs(G.zH,V,h,A)});
g.pV(J)})},cL9=function(G,B,a,V,x){x===-1?(a="decode "+g.I5(V,3),cc(G,!1,a)):x===2?(n5(G),G.B=!0):(G.V=0,G.X.stop(),x===1?(G.B=!1,a&&a.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&G.player.Y$(!0),x="pe."+(a==null?void 0:a.errorCode)+";ps."+(a==null?void 0:a.status),G.player.Ev("heartbeat.stop",2,G.Qd(V),x),g.wP("heartbeatActionPlayerHalted",SgC(a)),(B==null?0:B.videoTransitionEndpoint)&&a&&(B=B.videoTransitionEndpoint,(V=g.u(B,g.o0))&&RUJ(G,V,a,{itct:B==null?void 0:B.clickTrackingParams}))):(G.B=
!0,V=0,G.G&&a&&(V=Iz$(G,B,a),G.player.publish("livestatedata",a)),V?bJ(G,V):bJ(G)))},Iz$=function(G,B,a){var V=a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer,x=!(!V||!(V.switchStreamsImmediately||V.transitionTiming&&V.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
B=ZXh(G,B,V);var h=G.getVideoData(),e=G.player.getPlayerStateObject(G.getPlayerType()),w=e.isPlaying()&&!g.cF(h)&&!G.player.isAtLiveHead(G.getPlayerType());if(h.U().Ef()){var K,l=((K=G.player.Zc())==null?void 0:K.Nd())||{};l.status=a.status||"";l.dvr=""+ +w;l["switch"]=""+ +x;l.ended=""+ +!(!V||!V.displayEndscreen);G.player.FJ("heartbeat",l)}if(w&&!x)return B;x=V&&V.streamTransitionEndpoint&&g.u(V.streamTransitionEndpoint,g.o0);if((V&&V.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")G.getVideoData().transitionEndpointAtEndOfStream=
x;else if(x&&RUJ(G,x,a))return B;if(a.status.toUpperCase()==="OK"){x=V&&V.broadcastId;K=G.j&&G.j.liveStreamability&&G.j.liveStreamability.liveStreamabilityRenderer&&G.j.liveStreamability.liveStreamabilityRenderer.broadcastId;w=x!==K&&x!=null;if(!g.EN(h)||w){var k={video_id:h.videoId};h.hS&&(k.is_live_destination="1");k.disable_watch_next=!0;k.raw_watch_next_response=h.getWatchNextResponse();k.autonav_state=h.autonavState;k.oauth_token=h.oauthToken;k.force_gvi=h.B6;k.gB=h.gB;h.L&&(k.vss_credentials_token=
h.L,k.vss_credentials_token_type=h.iF);h.XJ&&(k.vvt=h.XJ);V=void 0;g.EN(h)?w&&(V=new jm("broadcastIdChanged",K+","+x),G.MW("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",a)):(x&&(V=new jm("formatsReceived",""+x)),G.MW("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",a));G.player.loadVideoByPlayerVars(k,void 0,void 0,void 0,V);return B}G.player.Za("heartbeat",G.getPlayerType())}V&&V.displayEndscreen&&(G.offlineSlate?
(G=G.offlineSlate,G.W=!0,G.Rt&&G.api.qg()):e.isBuffering()&&(h=((k=G.player.Zc())==null?void 0:k.Nd())||{},G.player.FJ("hbse",h,!0),G.player.qg(),G.player.pN("onLiveMediaEnded",a)));return B},ZXh=function(G,B,a){return G.player.S("web_player_use_heartbeat_poll_delay_ms")&&(G=Number(B==null?void 0:B.pollDelayMs))?G:(a=Number(a==null?void 0:a.pollDelayMs))?a:0},cc=function(G,B,a){var V=G.player.U();
if(!G.X.isActive()){G.X.stop();G.V++;var x=B?"heartbeat.net":"heartbeat.servererror";var h=G.getVideoData();if(h.jR||B&&!g.gB(G.getVideoData())&&!jCh(G)&&h.isLivePlayback)h=!1;else{var e,w;((w=G.heartbeatParams)==null?0:w.retries)?e=G.heartbeatParams.retries:e=h.EB||5;h=G.V>=e}h?(g.wP("heartbeatActionPlayerHalted",B?{enforcedPolicyToHaltOnNetworkFailure:!0}:SgC()),(B=G.getVideoData())&&B.isLivePlayback?G.player.Ev(x,1,"Se interrumpi\u00f3 la reproducci\u00f3n del video. Vuelve a intentarlo.",a):G.player.Ev(x,
1,"Se produjo un error de licencia con este video.",a)):(V.S("html5_report_non_fatal_heartbeat_error")&&G.player.G6(x,{msg:a}),bJ(G,G.L.getValue()),g.Ez(G.L))}},SgC=function(G){var B={enforcedPolicyToHaltOnNetworkFailure:!1};
G&&(B.serializedServerContext=G.additionalLoggingData);return B},n5=function(G){G.V=0;
G.X.stop();G.B=!1;G.sequenceNumber=0},mh3=function(G){var B=G.getVideoData(),a=G.player.U();
if(B.isLivePlayback)if(g.Bo(a.B)){G.G=!0;G.W=!0;if(!g.yI(a)||g.jQ(a))G.offlineSlate=new dhW(G.player),g.X(G,G.offlineSlate),g.SX(G.player,G.offlineSlate.element,4);(B=B.getPlayerResponse())&&B.playabilityStatus&&(G.j=B.playabilityStatus);var V;((V=G.j)==null?void 0:V.status)!=="UNPLAYABLE"&&(G.j?(V=ZXh(G,void 0,G.j.liveStreamability&&G.j.liveStreamability.liveStreamabilityRenderer))?bJ(G,V):bJ(G,7500):bJ(G,1E3))}else G.player.Ev("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.YC(B.GH,"heartbeat")&&G.player.Za("heartbeat",G.getPlayerType())},RUJ=function(G,B,a,V){var x=B&&B.videoId;
return x?(G.player.a9(x,Object.assign({},{autonav:"1"},V||{}),void 0,!0,!0,B,g.uv(G.getVideoData())),G.MW("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",a),!0):!1},vH$=function(G){return(G=G.player.getProgressState(G.getPlayerType()).ingestionTime)&&isFinite(G)?""+Math.floor(G*1E3):null},Dha=function(G){return(G=G.player.getCurrentTime(G.getPlayerType()))&&isFinite(G)?""+Math.floor(G*1E3):null},bXs=function(G){try{var B=JSON.parse(G);
return B!=null?B:void 0}catch(a){}},rL3={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
rL3={ERAS:["a.C.","d.C."],ERANAMES:["antes de Cristo","despu\u00e9s de Cristo"],NARROWMONTHS:"EFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"EFMAMJJASOND".split(""),MONTHS:"enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre".split(" "),STANDALONEMONTHS:"enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre".split(" "),SHORTMONTHS:"ene feb mar abr may jun jul ago sept oct nov dic".split(" "),STANDALONESHORTMONTHS:"ene feb mar abr may jun jul ago sept oct nov dic".split(" "),
WEEKDAYS:"domingo lunes martes mi\u00e9rcoles jueves viernes s\u00e1bado".split(" "),STANDALONEWEEKDAYS:"domingo lunes martes mi\u00e9rcoles jueves viernes s\u00e1bado".split(" "),SHORTWEEKDAYS:"dom lun mar mi\u00e9 jue vie s\u00e1b".split(" "),STANDALONESHORTWEEKDAYS:"dom lun mar mi\u00e9 jue vie s\u00e1b".split(" "),NARROWWEEKDAYS:"DLMMJVS".split(""),STANDALONENARROWWEEKDAYS:"DLMMJVS".split(""),SHORTQUARTERS:["T1","T2","T3","T4"],QUARTERS:["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre",
"4.\u00ba trimestre"],AMPMS:["a.m.","p.m."],DATEFORMATS:["EEEE, d 'de' MMMM 'de' y","d 'de' MMMM 'de' y","d MMM y","d/M/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1}, {0}","{1}, {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:0,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:6};
var OXC=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],$hh={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.W=xh$.prototype;g.W.l1=rL3.FIRSTDAYOFWEEK;g.W.Ug=rL3.FIRSTWEEKCUTOFFDAY;
g.W.clone=function(){var G=new xh$(this.date);G.l1=this.l1;G.Ug=this.Ug;return G};
g.W.getFullYear=function(){return this.date.getFullYear()};
g.W.getYear=function(){return this.getFullYear()};
g.W.getMonth=function(){return this.date.getMonth()};
g.W.getDate=function(){return this.date.getDate()};
g.W.getTime=function(){return this.date.getTime()};
g.W.getDay=function(){return this.date.getDay()};
g.W.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.W.getUTCMonth=function(){return this.date.getUTCMonth()};
g.W.getUTCDate=function(){return this.date.getUTCDate()};
g.W.getUTCDay=function(){return this.date.getDay()};
g.W.getUTCHours=function(){return this.date.getUTCHours()};
g.W.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.W.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.W.set=function(G){this.date=new Date(G.getFullYear(),G.getMonth(),G.getDate())};
g.W.setFullYear=function(G){this.date.setFullYear(G)};
g.W.setYear=function(G){this.setFullYear(G)};
g.W.setMonth=function(G){this.date.setMonth(G)};
g.W.setDate=function(G){this.date.setDate(G)};
g.W.setTime=function(G){this.date.setTime(G)};
g.W.setUTCFullYear=function(G){this.date.setUTCFullYear(G)};
g.W.setUTCMonth=function(G){this.date.setUTCMonth(G)};
g.W.setUTCDate=function(G){this.date.setUTCDate(G)};
g.W.add=function(G){if(G.years||G.months){var B=this.getMonth()+G.months+G.years*12,a=this.getYear()+Math.floor(B/12);B%=12;B<0&&(B+=12);a:{switch(B){case 1:var V=a%4!=0||a%100==0&&a%400!=0?28:29;break a;case 5:case 8:case 10:case 3:V=30;break a}V=31}V=Math.min(V,this.getDate());this.setDate(1);this.setFullYear(a);this.setMonth(B);this.setDate(V)}G.days&&(a=this.getYear(),B=a>=0&&a<=99?-1900:0,G=new Date((new Date(a,this.getMonth(),this.getDate(),12)).getTime()+G.days*864E5),this.setDate(1),this.setFullYear(G.getFullYear()+
B),this.setMonth(G.getMonth()),this.setDate(G.getDate()),p5(this,G.getDate()))};
g.W.Wx=function(G){return!(!G||this.getYear()!=G.getYear()||this.getMonth()!=G.getMonth()||this.getDate()!=G.getDate())};
g.W.toString=function(){var G=this.getFullYear(),B=G<0?"-":G>=1E4?"+":"";return[B+G_l(Math.abs(G),B?6:4),G_l(this.getMonth()+1,2),G_l(this.getDate(),2)].join("")+""};
g.W.valueOf=function(){return this.date.valueOf()};var X2l=new g.b4("addUpcomingEventReminderEndpoint");var qg3=new g.b4("removeUpcomingEventReminderEndpoint");var uwC=new g.b4("updateUpcomingEventReminderButtonStateCommand");var eUf=new g.b4("upcomingEventReminderButtonRenderer"),NN3=new g.b4("upcomingEventReminderButtonStateRenderer");g.t(Ux,g.uq);
Ux.prototype.updateMenuItems=function(){var G=this,B=hU9(this),a=0;a=0;for(var V={};a<B.length;V={rh:void 0},a++){var x=this.C[a];x||(x=new g.T({Z:"div",J:"ytp-reminder-menu-item",N:{role:"menuitem",tabindex:"0"},D:[{Z:"div",J:"ytp-reminder-menu-item-icon",cS:"{{icon}}"},{Z:"div",J:"ytp-reminder-menu-item-label",cS:"{{text}}"}]}),V.rh=a,x.listen("click",function(e){return function(){var w=e.rh;G.Bf();w=hU9(G)[w];G.publish("reminderMenuItemClicked",w.serviceEndpoint||w.command)}}(V)),x.iL(this.items),
this.C[a]=x);
var h=B[a];V=null;switch(h.icon&&h.icon.iconType){case "NOTIFICATIONS":V=BN$();break;case "NOTIFICATIONS_NONE":V=az2();break;case "NOTIFICATIONS_ACTIVE":V=g.jT()}h=h.text?g.tU(h.text):"";x.update({icon:V,text:h})}for(;a<this.C.length;)this.C.pop().dispose();a===0?this.Bf():this.xW(this.j)};
Ux.prototype.hide=function(){this.j&&this.j.removeAttribute("aria-haspopup");g.uq.prototype.hide.call(this)};
Ux.prototype.show=function(){this.j&&this.j.setAttribute("aria-haspopup","true");g.uq.prototype.show.call(this)};
Ux.prototype.yb=function(){g.wl(this.C);g.uq.prototype.yb.call(this)};g.t(Ox,g.T);
Ox.prototype.W=function(){if(this.toggleButtonRenderer){var G=this.toggleButtonRenderer;G.isToggled?this.C(G.toggledServiceEndpoint):this.C(G.defaultServiceEndpoint);G.isToggled=!G.isToggled;Ex(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Rt)this.j.Bf();else{var B=Kch(this);B&&this.C(B.serviceEndpoint||B.command);B=((G=g.u(B==null?void 0:B.command,g.tn))==null?void 0:G.commands)||[];a:{G=g.m(B);for(var a=G.next();!a.done;a=G.next()){var V=B=void 0;if(a=(B=g.u(a.value,g.dUl))==
null?void 0:(V=B.popup)==null?void 0:V.menuPopupRenderer){G=a;break a}}G=void 0}this.j||(this.j=new Ux(this.T,this.L),this.j.iL(this.element),g.X(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.C,this));B=this.j;B.menuPopupRenderer=G;B.updateMenuItems()}};
Ox.prototype.C=function(G){var B=g.u(G,X2l),a=g.u(G,qg3);if(G&&(B||a)){if(B){var V=B;var x="notification/add_upcoming_event_reminder"}else a&&(V=a,x="notification/remove_upcoming_event_reminder");if(x&&V&&V.params)for(k_J(this,x,V.params),G=g.m(V.commands||[]),B=G.next();!B.done;B=G.next())if((B=B.value)&&g.u(B,uwC)){this.X=g.u(B,uwC).state;Ex(this);break}}};g.t(dhW,g.T);g.W=dhW.prototype;g.W.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.W.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.W.uL=function(G){var B,a,V=G==null?void 0:(B=G.liveStreamability)==null?void 0:(a=B.liveStreamabilityRenderer)==null?void 0:a.offlineSlate;if(V){this.X=G;B=V.liveStreamOfflineSlateRenderer;B.canShowCountdown?this.PO():Cch(this,B);var x,h,e,w;if(a=G==null?void 0:(x=G.liveStreamability)==null?void 0:(h=x.liveStreamabilityRenderer)==null?void 0:(e=h.offlineSlate)==null?void 0:(w=e.liveStreamOfflineSlateRenderer)==null?void 0:w.thumbnail){x=0;h=null;e=a.thumbnails;for(w=0;w<e.length;w++)e[w].width>
x&&(x=e[w].width||0,h=e[w].url);h&&(this.background.style.backgroundImage="url("+h+")")}else this.background.style.backgroundImage="";B.actionButtons||B.reminderButton?(this.j||(this.j=new Ox(this.api),this.j.iL(this.d1("ytp-offline-slate-buttons")),g.X(this,this.j)),Wcl(this.j,B.actionButtons&&B.actionButtons[0],B.reminderButton)):this.j&&Wcl(this.j,null,null);this.X=G}else this.X=null;this.DP()};
g.W.DP=function(G){if(this.api.getPresentingPlayerType()===8)var B=!0;else{var a=this.api.getPlayerStateObject(),V=this.getVideoData();B=V.isLivePlayback&&(a.isBuffering()||g.F(a,2)||g.F(a,64));var x=V.autonavState===2&&g.F(a,2);a=a.isPlaying()&&!g.cF(V)&&!this.api.isAtLiveHead(void 0,!0);B=B&&!a&&!x}B&&this.X?this.Rt?(G==null?0:g.CY(G,2))&&!this.getVideoData().Wh&&(g.WC(this.element,"ytp-offline-slate-collapsed"),this.G.stop(),g.WC(this.C,"ytp-offline-slate-bar-fade"),this.L.start()):(this.show(),
this.G.start(),this.api.publish("offlineslatestatechange"),this.W&&this.api.qg()):this.Rt&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.W.PO=function(){var G,B,a,V,x=(G=this.X)==null?void 0:(B=G.liveStreamability)==null?void 0:(a=B.liveStreamabilityRenderer)==null?void 0:(V=a.offlineSlate)==null?void 0:V.liveStreamOfflineSlateRenderer;x&&(G=Math.floor(g.G$()/1E3),B=x.canShowCountdown&&Number(x.scheduledStartTime),!B||B<=G?(Cch(this,x),this.countdownTimer.stop()):(Cch(this,x,g.E5(B-G)),g.iC(this.countdownTimer)))};
g.W.yb=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.T.prototype.yb.call(this)};jm.prototype.X=function(G){return this.trigger&&G.trigger?this.module===G.module&&this.trigger===G.trigger&&this.j===G.j:!1};
jm.prototype.isExpired=function(){return(0,g.yT)()-this.C>6E4};
jm.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.t(p2k,g.go);g.W=p2k.prototype;g.W.yb=function(){n5(this);this.player.KD("heartbeat");g.go.prototype.yb.call(this)};
g.W.onCueRangeEnter=function(){this.W=!0;bJ(this,2E3)};
g.W.T5=function(G){this.heartbeatParams=G;bJ(this,2E3)};
g.W.SU=function(G){var B;this.player.getPresentingPlayerType()!==8&&((B=this.j)==null?void 0:B.status)!=="UNPLAYABLE"&&(g.F(G.state,2)||g.F(G.state,64)?(n5(this),this.G&&(this.W=!0,bJ(this,1E3))):(g.F(G.state,1)||g.F(G.state,8))&&bJ(this,2E3))};
g.W.hm=function(){this.player.getPresentingPlayerType()!==3&&bJ(this,2E3)};
g.W.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.W.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.W.v6=function(G){switch(G){case 4:case 3:return!1}return!0};
g.W.MW=function(G,B,a){G={trigger:G,reason:B};a&&(G.serializedServerContext=a.additionalLoggingData);g.wP("heartbeatActionPlayerTransitioned",G)};
g.W.Qd=function(G){var B="LICENSE",a=bXs(G);if(a)return a.reason||g.QY[B]||"";if(G=G.match(yL8))if(G=Number(G[1]))B=(B=$hh[G.toString()])?B:"LICENSE";return g.QY[B]||""};
g.W.Jx=function(){return!!this.offlineSlate&&this.offlineSlate.Rt};
var yL8=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.Is("heartbeat",p2k);})(_yt_player);
